"""How much of the pursuit's effect survives a smaller target set.

A theoretical analysis with no simulation involved: how many satellites an adversary would need to
attack, and which ones, to obtain a partial rather than a total loss of the connection.

Two sources of data, both already collected, so no new run is required.

  1. The attack plan, a purely geometric analysis with no routing involved: for each visibility
     window, which satellites Fucino can reach. From this comes each satellite's visibility weight,
     the total time it spends in view. This criterion is observable from outside, since it follows
     from public orbital elements, and does not require knowing the network's internal routing
     decisions.
  2. The baseline trace, which records the satellite each message actually used as its first hop.
     For any candidate set, the number of messages that would have been destroyed follows by
     counting.

The order in which satellites are added to the set is therefore the visibility ranking, which an
adversary could construct, rather than the traffic ranking, which it could not.
"""

import json
import os
import pickle
from collections import Counter

from dsns.message import MessageSentEvent

_REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))

PLAN_PATH = os.path.join(_REPO_ROOT, "results", "pursuit", "dynamic_attack_plan_result.json")
BASELINE_MESSAGEPATH = os.path.join(
    _REPO_ROOT, "results", "message_paths", "normal_traffic",
    "iridium-g2g-eu_usa-best_effort-0.0-point_to_point-target5_0-1-messagepath.pickle",
)

FUCINO = 5
TOTAL_MESSAGES = 600   # messages generated by the baseline run


def load_visibility_weight(plan_path: str = PLAN_PATH):
    """Visibility weight per satellite: the total duration of the windows in which it is in view.

    A purely geometric analysis, with no routing involved.
    """
    with open(plan_path) as f:
        data = json.load(f)
    plan = [(s, e, frozenset(sats)) for s, e, sats in data["plan"]]

    weight = {}
    for start, end, sats in plan:
        for sat in sats:
            weight[sat] = weight.get(sat, 0.0) + (end - start)
    return weight


def load_real_traffic_counts(messagepath: str = BASELINE_MESSAGEPATH):
    """How often each satellite is actually chosen as a message's first hop in the baseline run.

    Read from the unattacked trace, this is the only reliable basis for estimating how much traffic
    a given target set would destroy.
    """
    with open(messagepath, "rb") as f:
        events = pickle.load(f)
    fucino_hops = [e for e in events if isinstance(e, MessageSentEvent) and e.source == FUCINO]
    return Counter(e.destination for e in fucino_hops), len(fucino_hops)


def build_visibility_ranking(weight: dict):
    """Orders satellites by decreasing visibility weight, the externally observable criterion.

    On ties, sorted() is stable, so equally weighted satellites keep their order of first appearance
    in the weights, which is chronological within the plan rather than a deliberate tie-break. Stated
    here for reproducibility.
    """
    return sorted(weight.keys(), key=lambda sat: -weight[sat])


def coverage_curve(ranking, dest_counts: Counter, total_messages: int = TOTAL_MESSAGES):
    """Cumulative share of the real traffic destroyed by attacking the first K satellites."""
    rows = []
    cum = 0
    for k, sat in enumerate(ranking, 1):
        cum += dest_counts.get(sat, 0)
        rows.append({
            "k": k,
            "satellite_added": sat,
            "cumulative_messages_hit": cum,
            "coverage_pct_of_total": round(100 * cum / total_messages, 1),
        })
    return rows


def main():
    weight = load_visibility_weight()
    dest_counts, n_resolved_hops = load_real_traffic_counts()

    ranking = build_visibility_ranking(weight)

    print("Ranking per peso di visibilita' (Fonte 1: dynamic_attack_plan_result.json), decrescente")
    print("=" * 78)
    for rank, sat in enumerate(ranking, 1):
        real_count = dest_counts.get(sat, 0)
        print(f"  {rank:2d}. sat {sat:3d}  visibility={weight[sat]:6.0f}s   "
              f"observed traffic={real_count:3d} msg ({100*real_count/TOTAL_MESSAGES:4.1f}%)")

    curve = coverage_curve(ranking, dest_counts)
    print(f"\nCoverage curve (expected drop rate over {TOTAL_MESSAGES} messages)")
    print("=" * 78)
    for row in curve:
        print(f"  K={row['k']:2d}  +sat {row['satellite_added']:3d}  ->  "
              f"copertura cumulativa: {row['coverage_pct_of_total']:5.1f}%")

    output = {
        "fucino": FUCINO,
        "total_messages": TOTAL_MESSAGES,
        "n_resolved_hops_baseline": n_resolved_hops,
        "visibility_weight": {str(sat): w for sat, w in weight.items()},
        "real_traffic_counts": {str(sat): cnt for sat, cnt in dest_counts.items()},
        "ranking_by_visibility": ranking,
        "coverage_curve": curve,
    }
    out_path = os.path.join(os.path.dirname(__file__), "reduced_target_analysis_result.json")
    with open(out_path, "w") as f:
        json.dump(output, f, indent=2)
    print(f"\n[OK] Results saved to {out_path}")


if __name__ == "__main__":
    main()
